const species = [
    {
      "dbnumber": 100,
      "iucncategory": "EX",
      "currentcategoryinrm": "EX = Extinta",
      "scientificname": "Tristagma leichtlinii",
      "commonname": "Flor de la virgen",
      "cardname": "Flor de la virgen",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Magnoliophyta",
      "class": "Liliopsida",
      "haverecord": "MMA WORD",
      "description": "sample description text",
      "image": "img-flor-de-la-virgen.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 101,
      "iucncategory": "CR",
      "currentcategoryinrm": "CR = En peligro crítico",
      "scientificname": "Alsodes laevis",
      "commonname": "Sapo de pecho espinoso de Potrero",
      "cardname": "Sapo de pecho espinoso de Potrero",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Amphibia",
      "class": "Amphibia",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-sapo-de-pecho-espinoso-de-potrero.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 102,
      "iucncategory": "CR",
      "currentcategoryinrm": "CR = En peligro crítico",
      "scientificname": "Euathlus condorito",
      "commonname": "Araña pollito",
      "cardname": "Tarántula",
      "endemictochile": "Araña pollito",
      "kingdom": "SI",
      "phylumdivition": "Animalia",
      "class": "Arthropoda",
      "haverecord": "Arachnida",
      "description": "sample description text",
      "image": "img-arana-pollito.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 103,
      "iucncategory": "CR",
      "currentcategoryinrm": "CR = En peligro crítico",
      "scientificname": "Numenius borealis",
      "commonname": "Zarapito boreal; Chorlo campero; Chorlo esquimal",
      "cardname": "Zarapito boreal",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Aves",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-zarapito-boreal.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 104,
      "iucncategory": "CR",
      "currentcategoryinrm": "CR = En peligro crítico",
      "scientificname": "Adiantum pearcei",
      "commonname": "Palito negro",
      "cardname": "Palito negro",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Pteridophyta",
      "class": "Filicopsida",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-palito-negro.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 105,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Nematogenys inermis",
      "commonname": "Bagre",
      "cardname": "Bagre grande",
      "endemictochile": "Bagre grande",
      "kingdom": "SI",
      "phylumdivition": "Animalia",
      "class": "Chordata",
      "haverecord": "Actinopterygii",
      "description": "sample description text",
      "image": "img-bagre-grande.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 106,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Nycticryphes semicollaris",
      "commonname": "Becacina pintada",
      "cardname": "Aguatero",
      "endemictochile": "Becacina pintada",
      "kingdom": "NO",
      "phylumdivition": "Animalia",
      "class": "Chordata",
      "haverecord": "Aves",
      "description": "sample description text",
      "image": "img-becacina-pintada.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 107,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Mordacia lapicida",
      "commonname": "Komofilú",
      "cardname": "Lamprea de agua dulce",
      "endemictochile": "Anguila",
      "kingdom": "Lamprea de agua dulce",
      "phylumdivition": "SI",
      "class": "Animalia",
      "haverecord": "Chordata",
      "description": "sample description text",
      "image": "img-lamprea-de-agua-dulce.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 108,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Bombus dahlbomii",
      "commonname": "Abejorro,Duillin (mapudungún), Don Basilio, Abejorro gigante de La Patagonia, Moscardón, Diwmeñ (mapudungún)",
      "cardname": "Abejorro colorado",
      "endemictochile": "",
      "kingdom": "",
      "phylumdivition": "",
      "class": "",
      "haverecord": "",
      "description": "sample description text",
      "image": "img-abejorro-colorado.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 109,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Aegla laevis",
      "commonname": "Pancora",
      "cardname": "Piñacha",
      "endemictochile": "llashka",
      "kingdom": "Pancora",
      "phylumdivition": "SI",
      "class": "Animalia",
      "haverecord": "Arthropoda",
      "description": "sample description text",
      "image": "img-pancora.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 110,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Pristidactylus valeriae",
      "commonname": "Gruñidor de Valeria",
      "cardname": "Gruñidor de Valeria",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Reptilia",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-grunidor-de-valeria.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 111,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Cyttaria berteroi",
      "commonname": "Pinatra, Pina, Piña, Curacucha",
      "cardname": "Curacucha",
      "endemictochile": "NO",
      "kingdom": "Fungi",
      "phylumdivition": "Ascomycota",
      "class": "Leotiomycetes",
      "haverecord": "",
      "description": "sample description text",
      "image": "img-curacucha.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 112,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Tecophilaea cyanocrocus",
      "commonname": "Azulillo",
      "cardname": "Azulillo",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Magnoliophyta",
      "class": "Liliopsida",
      "haverecord": "No",
      "description": "sample description text",
      "image": "img-azulillo.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 113,
      "iucncategory": "EN",
      "currentcategoryinrm": "EN = En Peligro",
      "scientificname": "Avellanita bustillosii",
      "commonname": "Avellanita; Nogal del monte",
      "cardname": "Avellanita",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Magnoliophyta",
      "class": "Magnoliopsida",
      "haverecord": "MMA WORD",
      "description": "sample description text",
      "image": "img-avellanita.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 114,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Galaxias maculatus",
      "commonname": "Puye; Puyen; Peladilla; Angula; Coltrao; Truchita",
      "cardname": "Puye",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Actinopterygii",
      "haverecord": "MMA WORD PDF",
      "description": "sample description text",
      "image": "img-puye.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 115,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Calyptocephalella gayi",
      "commonname": "Rana chilena",
      "cardname": "Rana chilena",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Amphibia",
      "haverecord": "No",
      "description": "sample description text",
      "image": "img-rana-chilena.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 116,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Cyanoliseus patagonus",
      "commonname": "Tricahue; Loro barranquero",
      "cardname": "Tricahue",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Aves",
      "haverecord": "MMA WORD",
      "description": "sample description text",
      "image": "img-tricahue.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 117,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Copestylum nigripes",
      "commonname": "Mosco azul de cara roja; Mosco de los cactus de cara roja",
      "cardname": "Mosco azul de cara roja",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Arthropoda",
      "class": "Insecta",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-mosco-azul-de-cara-roja.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 118,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Lama guanicoe",
      "commonname": "Guanaco; Amura; Luan; Hueque",
      "cardname": "Guanaco",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Mammalia",
      "haverecord": "MMA WORD",
      "description": "sample description text",
      "image": "img-guanaco.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 119,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Leopardus guigna",
      "commonname": "Güiña; Gato güiña; Kodkod",
      "cardname": "Gato güiña",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Mammalia",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-gato-guina.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 120,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Lycalopex culpaeus",
      "commonname": "Zorro culpeo; Zorro colorado; Culpeo; Khamake; Culpem; Zorro colorado de Tierra del Fuego; Zorro culpeo de Tierra del Fuego",
      "cardname": "Zorro culpeo",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Mammalia",
      "haverecord": "No",
      "description": "sample description text",
      "image": "img-zorro-culpeo.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 121,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Liolaemus gravenhorsti",
      "commonname": "Lagartija de Gravenhorst",
      "cardname": "Lagartija de Gravenhorst",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Reptilia",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-lagartija-de-gravenhorst.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 122,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Austrocedrus chilensis",
      "commonname": "Ciprés de Cordillera, Ciprés, Len, Lahuán",
      "cardname": "Ciprés de Cordillera",
      "endemictochile": "NO",
      "kingdom": "Plantae",
      "phylumdivition": "",
      "class": "",
      "haverecord": "",
      "description": "sample description text",
      "image": "img-cipres-de-cordillera.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 123,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Aextoxicon punctatum",
      "commonname": "Olivillo",
      "cardname": "Teque",
      "endemictochile": "Tique",
      "kingdom": "Palo muerto",
      "phylumdivition": "Aceitunillo",
      "class": "Olivillo",
      "haverecord": "NO",
      "description": "sample description text",
      "image": "img-olivillo.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 124,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Jubaea chilensis",
      "commonname": "Palma chilena; Palma de coquitos; Palma de miel; Palmera chilena",
      "cardname": "Palma chilena",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Magnoliophyta",
      "class": "Liliopsida",
      "haverecord": "MMA PDF x2",
      "description": "sample description text",
      "image": "img-palma-chilena.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 125,
      "iucncategory": "VU",
      "currentcategoryinrm": "VU = Vulnerable",
      "scientificname": "Persea lingue",
      "commonname": "Lingue",
      "cardname": "Lingue",
      "endemictochile": "NO",
      "kingdom": "Plantae",
      "phylumdivition": "Magnoliophyta",
      "class": "Magnoliopsida",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-lingue.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 126,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Strix rufipes",
      "commonname": "Concón; Lechuza bataraz; Kongkong",
      "cardname": "Concón",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Aves",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-concon.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 127,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Castnia eudesmia",
      "commonname": "Mariposa del chagual",
      "cardname": "Mariposa del chagual",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Arthropoda",
      "class": "Insecta",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-mariposa-del-chagual.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 128,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Puma concolor",
      "commonname": "Puma",
      "cardname": "León de montaña",
      "endemictochile": "León americano",
      "kingdom": "Trapial (mapudungun)",
      "phylumdivition": "Puma",
      "class": "NO",
      "haverecord": "Animalia",
      "description": "sample description text",
      "image": "img-puma.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 129,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Callopistes maculatus",
      "commonname": "Iguana; Iguana chilena",
      "cardname": "Iguana chilena",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Reptilia",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-iguana-chilena.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 130,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Caloplaca tucumanensis",
      "commonname": "Liquen",
      "cardname": "Liquen",
      "endemictochile": "NO",
      "kingdom": "Fungi",
      "phylumdivition": "Ascomycota",
      "class": "Lecanoromycetes",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-liquen.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 131,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Costesia macrocarpa",
      "commonname": "Musgo de Costes",
      "cardname": "Musgo de Costes",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Bryophyta",
      "class": "Bryopsida",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-musgo-de-costes.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 132,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Pellaea myrtillifolia",
      "commonname": "Coca; Yerba coca; Hierba coca; Lendo del cerro",
      "cardname": "Lendo del cerro",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Pteridophyta",
      "class": "Filicopsida",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-lendo-del-cerro.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 133,
      "iucncategory": "NT",
      "currentcategoryinrm": "NT = Casi amenazada",
      "scientificname": "Kageneckia angustifolia",
      "commonname": "Frangel; Olivillo; Olivillo de la cordillera; Pulpica",
      "cardname": "Frangel",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Magnoliophyta",
      "class": "Magnoliopsida",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-frangel.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 134,
      "iucncategory": "LC",
      "currentcategoryinrm": "LC = Preocupación menor",
      "scientificname": "Acanthinodera cumingii",
      "commonname": "Madre de la Culebra",
      "cardname": "Matabuey",
      "endemictochile": "Matacaballo",
      "kingdom": "Llico",
      "phylumdivition": "Jotezón del monte",
      "class": "Madre de la Culebra",
      "haverecord": "SI",
      "description": "sample description text",
      "image": "img-madre-de-la-culebra.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 135,
      "iucncategory": "LC",
      "currentcategoryinrm": "LC = Preocupación menor",
      "scientificname": "Parastacus pugnax",
      "commonname": "Camarón de las vegas del centro de Chile",
      "cardname": "Camarón de vega",
      "endemictochile": "Camarón excavador",
      "kingdom": "Camarón excavador",
      "phylumdivition": "SI",
      "class": "Animalia",
      "haverecord": "Arthropoda",
      "description": "sample description text",
      "image": "img-camaron-excavador.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 136,
      "iucncategory": "LC",
      "currentcategoryinrm": "LC = Preocupación menor",
      "scientificname": "Liolaemus tenuis",
      "commonname": "Lagartija esbelta; Lagartija de colores",
      "cardname": "Lagartija de colores",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Reptilia",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-lagartija-de-colores.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 137,
      "iucncategory": "LC",
      "currentcategoryinrm": "LC = Preocupación menor",
      "scientificname": "Descolea antarctica",
      "commonname": "Hongo",
      "cardname": "Hongo",
      "endemictochile": "NO",
      "kingdom": "Fungi",
      "phylumdivition": "Basidiomycota",
      "class": "Basidiomycetes",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-hongo.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 138,
      "iucncategory": "LC",
      "currentcategoryinrm": "LC = Preocupación menor",
      "scientificname": "Eriosyce subgibbosa",
      "commonname": "Quisquito; Cacto rosado",
      "cardname": "Quisquito",
      "endemictochile": "SI",
      "kingdom": "Plantae",
      "phylumdivition": "Magnoliophyta",
      "class": "Magnoliopsida",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-quisquito.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 139,
      "iucncategory": "DD",
      "currentcategoryinrm": "DD = Datos insuficientes",
      "scientificname": "Moluchia castanea",
      "commonname": "Cucaracha; Molukia ámbar",
      "cardname": "Cucaracha",
      "endemictochile": "SI",
      "kingdom": "Animalia",
      "phylumdivition": "Arthropoda",
      "class": "Insecta",
      "haverecord": "MMA PDF",
      "description": "sample description text",
      "image": "img-cucaracha.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    },
    {
      "dbnumber": 140,
      "iucncategory": "DD",
      "currentcategoryinrm": "DD = Datos insuficientes",
      "scientificname": "Lasiurus cinereus",
      "commonname": "Murciélago Ceniciento",
      "cardname": "Murciélago Ceniciento",
      "endemictochile": "NO",
      "kingdom": "Animalia",
      "phylumdivition": "Chordata",
      "class": "Mammalia",
      "haverecord": "",
      "description": "sample description text",
      "image": "img-murcielago-ceniciento.jpg",
      "attack": 10,
      "defence": 10,
      "cost": 10,
      "hitpoints": 100,
      "text1": "text 1 sample",
      "text2": "text 2 sample",
      "text3": "text 3 sample",
      "color1": "#cccccc",
      "color2": "#bbbbbb",
      "color3": "#aaaaaa",
      "textcolor1": "#222222",
      "textcolor2": "#333333",
      "textcolor3": "#444444",
      "other": " "
    }
        // ,{
    //   "iucncategory": "EW",
    //   "dbnumber": 141,
    //   "currentcategoryinrm": "EW= Extinta en estado silvestre",
    //   "scientificname": "-",
    //   "commonname": "-",
    //   "cardname": "",
    //   "endemictochile": "-",
    //   "kingdom": "-",
    //   "phylumdivition": "-",
    //   "class": "-",
    //   "haverecord": "-",
    //   "description": "sample description text",
    //   "imagimg--.jpg",
  
    //   "attack": 10,
    //   "defence": 10,
    //   "cost": 10,
    //   "hitpoints": 100,
    //   "text1": "text 1 sample",
    //   "text2": "text 2 sample",
    //   "text3": "text 3 sample",
    //   "color1": "#cccccc",
    //   "color2": "#bbbbbb",
    //   "color3": "#aaaaaa",
    //   "textcolor1": "#222222",
    //   "textcolor2": "#333333",
    //   "textcolor3": "#444444",
    //   "other": " "
    // }
  ]
